name: CI Pipeline - Notes App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show files
      run: ls -la

    - name: Build Docker Image
      run: docker build -t notes-app:ci ./app

      docker run -d -p 5000:5000 \
        -e FILE_PATH=/data/notes.txt \
        -e APP_PASSWORD=admin \
        notes-app:ci
      - name: Wait for app to start
        run: sleep 5

      - name: Verify app running
        run: curl http://localhost:5000
